### ISSUE TITLE
Don't use Link with external links

### ISSUE THREAD

**Issue by lorensr** [apollographql/gatsby-theme-apollo#192]
https://github.com/apollographql/apollo/ has this in its `docs/gatsby-config.js`:

```
sidebarCategories: {
          null: [
            'index',
            'intro/platform',
            'intro/benefits',
            '[Guided tutorials](https://odyssey.apollographql.com/?utm_source=apollo_docs&utm_medium=referral&utm_campaign=docs_sidebar)',
          ],
```

which results in this in the browser console:

```
External link https://odyssey.apollographql.com/?utm_source=apollo_docs&utm_medium=referral was detected in a Link component. Use the Link component only for internal links. See: https://gatsby.dev/internal-links 
    at GatsbyLink (eval at ES6ProxyComponentFactory (http://localhost:8000/commons.js:74681:10), <anonymous>:14:7)
    at http://localhost:8000/commons.js:10143:30
```

**Comment by trevorblades** [comment]
Just tried to reproduce this and I wasn't able to. Please reopen if this is still a problem.
