### ISSUE TITLE
Make build errors more fatal.

### ISSUE THREAD

**Issue by abernix** [apollographql/gatsby-theme-apollo#38]
Currently, if there is an error in the build, the `gatsby build` command still seems to exit with a truthy value.  This causes Netlify to think that the build was successful, and gives the impression that everything is _okay_, when it is in-fact going to break the documentation entirely if the PR is merged.

As a concrete example, the error shown on [this Netlify deploy](https://app.netlify.com/sites/apollo-server-docs/deploys/5cc2e0f9071909000b40f3c2) from https://github.com/apollographql/apollo-server/pull/2616 (but also reproducible locally below, basically, the file referenced in the config is missing because of human error — i.e. `uploads` vs `upload` naming inconsistency):

```sh
$ npx gatsby build --prefix-paths
success open and validate gatsby-configs — 0.021 s
success load plugins — 0.207 s
success onPreInit — 0.002 s
success delete html and css files from previous builds — 0.004 s
success initialize cache — 0.007 s
success copy gatsby files — 0.190 s
success onPreBootstrap — 0.016 s
success source and transform nodes — 0.022 s
success building schema — 0.228 s
error Error: Doc not found: docs/source/features/file-uploads.md@HEAD
    at getContents (/Users/jesse/Dev/apollo/apollo-platform-devkit/packages/apollo-server/docs/node_modules/gatsby-theme-apollo-docs/gatsby-node.js:151:21)
    at Promise.all.sidebarItems.map (/Users/jesse/Dev/apollo/apollo-platform-devkit/packages/apollo-server/docs/node_modules/gatsby-theme-apollo-docs/gatsby-node.js:64:28)
    at Array.map (<anonymous>)
    at getContents (/Users/jesse/Dev/apollo/apollo-platform-devkit/packages/apollo-server/docs/node_modules/gatsby-theme-apollo-docs/gatsby-node.js:52:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
success createPages — 2.395 s
success createPagesStatefully — 0.028 s
success onPreExtractQueries — 0.000 s
success update schema — 0.101 s
success extract queries from components — 0.162 s
success run static queries — 0.021 s — 3/3 148.13 queries/second
success run page queries — 0.058 s — 16/16 279.38 queries/second
success write out page data — 0.008 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.003 s

info bootstrap finished - 7.706 s

error (node:55501) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
error (node:55501) DeprecationWarning: Resolver#doResolve: The type arguments (string) is now a hook argument (Hook). Pass a reference to the hook instead.
success Building production JavaScript and CSS bundles — 23.555 s
success Building static HTML for pages — 4.251 s — 16/16 14.08 pages/second
info Done building in 35.521 sec
```

Is there a way to make that `error` more catastrophic and have the build immediately exit with a non-zero error code (i.e. `process.exit(1)`)?  That should cause the Netlify preview deploy status to not be green ✅ and give us the heads-up we need to avoid breaking documentation ❌.

**Comment by trevorblades** [comment]
This is resolved now!
